name: fila_postinho_front
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  shimmer: ^3.0.0
  animate_do: ^3.0.2
  shared_preferences: ^2.2.2
  provider: 6.1.2
  flutter_blue_plus: ^1.31.17
  cupertino_icons: ^1.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true